image: Visual Studio 2017

environment:
  matrix:
    - version: 1.31.0
      variant: windowsservercore-ltsc2019-gnu
    - version: 1.31.0
      variant: windowsservercore-1803-gnu
    - version: 1.31.0
      variant: windowsservercore-1709-gnu
    - version: 1.31.0
      variant: windowsservercore-ltsc2016-gnu
    - version: 1.31.0
      variant: windowsservercore-ltsc2019-msvc
    - version: 1.31.0
      variant: windowsservercore-1803-msvc
    - version: 1.31.0
      variant: windowsservercore-1709-msvc
    - version: 1.31.0
      variant: windowsservercore-ltsc2016-msvc

build_script:
  - cmd: appveyor-retry docker build --pull -t rust %version%/windows/%variant%

after_build:
  - ps: docker images

test_script:
  - cmd: docker run --rm rust cargo install --example toml2json toml --vers 0.4.4
