jobs:
- job: windowsservercore_1803_gnu
  pool:
    vmImage: 'win1803'
  steps:
  - script: docker build --pull -t rust 1.31.0/windows/windowsservercore-1709-gnu
  - script: docker images
  - script: docker run --rm rust cargo install --example toml2json toml --vers 0.4.4

